apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
  namespace: development
type: Opaque
stringData:
  azurestorageaccountname: $azurestorageaccountname
  azurestorageaccountkey: $azurestorageaccountkey